symlink: allow hardware-configuration to be missing
Signed-off-by: Jakub Sokołowski <panswiata@gmail.com>
Signed-off-by: Jakub Sokołowski <jakub@status.im>

diff --git a/symlink b/symlink
--- a/symlink
+++ b/symlink
@@ -5,25 +5,25 @@ if [[ ! -z "$1" ]]; then
     HOST="$1"
 fi
 
-FILES=(
-  "secrets.nix"
-  "hosts/${HOST}/configuration.nix" 
-  "hosts/${HOST}/hardware-configuration.nix" 
-)
-
-for FILE in ${FILES[@]}; do
-    if [[ ! -e "${FILE}" ]]; then
-        echo "Missing '${FILE}' file!" >&2
-        exit 1
-    fi
-done
+if [[ ! -e "secrets.nix" ]]; then
+    echo "Missing 'secrets.nix' file!" >&2; exit 1;
+fi
+if [[ ! -e "hosts/${HOST}/configuration.nix" ]]; then
+    echo "Missing 'hosts/${HOST}/configuration.nix' file!" >&2; exit 1;
+fi
+if [[ ! -e "hosts/${HOST}/hardware-configuration.nix" ]]; then
+    echo "Missing 'hosts/${HOST}/hardware-configuration.nix' file!" >&2;
+fi
 
 # symlink host config
 ln -vsf "${PWD}/hosts/${HOST}/configuration.nix" "${PWD}"
 ln -vsf "${PWD}/hosts/${HOST}/hardware-configuration.nix" "${PWD}"
 
 # and then the whole dir
-if [[ "${PWD}" != "/etc/nixos" ]]; then
-    rm -r "/etc/nixos"
-    ln -vsf "${PWD}" "/etc/nixos"
+if [[ -h "/etc/nixos" ]]; then
+    echo "The /etc/nixos path is already a symlink!" >&2
+    ls -l "/etc/nixos"
+elif [[ "${PWD}" != "/etc/nixos" ]]; then
+    sudo rm -rf "/etc/nixos"
+    sudo ln -vsf "${PWD}" "/etc/nixos"
 fi
